#!/bin/bash

FILE=test/Main.hs
PRAGMA=pragma

clear
stack runhaskell $FILE | grep -Ev '^(\[Peekaboo\])'

inotifywait -q -m -e close_write $FILE |
while read -r filename event; do

  OUTPUT=`stack runhaskell $FILE | grep -Ev '^(\[Peekaboo\])'`
  clear
  echo "$OUTPUT"

done
