name:                PropProver
version:             0.1.0.0
github:              "agustinmista/PropProver"
license:             BSD3
author:              "Agustín Mista"
maintainer:          "mista@chalmers.se"
copyright:           "2019 Agustín Mista"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/agustinmista/PropProver#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- Peekaboo

library:
  source-dirs: src

tests:
  Test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Peekaboo.Monadic
    - -fplugin-opt=Peekaboo.Monadic:$
    dependencies:
    - PropProver
